name: generate-mfa-token
description: Generate MFA token by taking MFA secret key as input
inputs:
  mfa-secret-key:
    description: MFA secret key
    required: true
runs:
  using: composite
  steps:
  - id: install-dependencies
    run: |
      pip install -r ${{ github.action_path }}/scripts/generate_mfa/requirements.txt
      chmod +x ${{ github.action_path }}/scripts/generate_mfa/generate_mfa.sh
      /usr/bin/python --version
    shell: bash
  - id: generate-token
    env:
      AWS_MFA_SECRET_KEY: ${{ inputs.mfa-secret-key }}
    run: echo "AWS_MFA_OTP=$(${{ github.action_path }}/scripts/generate_mfa/generate_mfa.sh)" >> $GITHUB_OUTPUT
    shell: bash
outputs:
  aws-mfa-otp:
    description: aws MFA OTP
    value: ${{ steps.generate-token.outputs.AWS_MFA_OTP }}