name: "Create/Update Infra on AWS"
on:
  push:
    branches:
      - 'main'
jobs:
  provision:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Generate AWS MFA token
        uses:  ./.github/actions/generate_aws_mfa
        with:
          mfa-secret-key: ${{ secrets.AWS_MFA_TOTP_KEY }}
