name: "Create/Update Infra on AWS"
on:
  push:
    branches:
      - 'prod/*'
      - 'staging/*'
      - 'dev/*'
jobs:
  prepare:
    runs-on: 'ubuntu-latest'
    outputs:
      target-env: ${{ steps.get-env-details.outputs.target-env }}
      target-aws-account: ${{ steps.get-env-details.outputs.target-aws-account }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Identify Environment
      id: get-env-details
      run: |
        branch_name="${{ github.ref }}"
        branch_prefix="${branch_name#refs/heads/}"
        aws_acnt=""
        target_env=""
        case ${branch_prefix} in
          prod*)
            target_env="PROD"
            aws_acnt="${branch_prefix#prod/}"
            ;;
          staging*)
            target_env="STAGING"
            aws_acnt="${branch_prefix#staging/}"
            ;;
          dev*)
            target_env="DEV"
            aws_acnt="${branch_prefix#dev/}"
            ;;
        esac
        echo "target-env=${target_env}" >> "$GITHUB_OUTPUT"
        echo "target-aws-account=${aws_acnt}" >> "$GITHUB_OUTPUT"
        echo "**TARGET ENV** = ${target_env}" >> "$GITHUB_STEP_SUMMARY"
        echo "**TARGET AWS ACCOUNT** = ${aws_acnt}" >> "$GITHUB_STEP_SUMMARY"
  start-prod:
    permissions:
      id-token: write
      contents: read
    needs:
    - prepare
    if: ${{github.event.job.prepare.outputs.target-env}} == "PROD"
    name: Prod-AWS-Provision
    uses: ./.github/workflows/prod_aws.yml
    with:
      target-env: ${{github.event.job.prepare.outputs.target-env}}
      target-aws-account: ${{github.event.job.prepare.outputs.target-aws-account}}
  start-staging:
    needs:
    - prepare
    if: ${{github.event.job.prepare.outputs.target-env}} == "STAGING"
    name: Staging-AWS-Provision
    uses: ./.github/workflows/staging_aws.yml
    with:
      target-env: ${{github.event.job.prepare.outputs.target-env}}
      target-aws-account: ${{github.event.job.prepare.outputs.target-aws-account}}
  start-dev:
    needs:
    - prepare
    if: ${{github.event.job.prepare.outputs.target-env}} == "DEV"
    name: Dev-AWS-Provision
    uses: ./.github/workflows/dev_aws.yml
    with:
      target-env: ${{github.event.job.prepare.outputs.target-env}}
      target-aws-account: ${{github.event.job.prepare.outputs.target-aws-account}}