name: "Create/Update Infra on AWS"
on:
  push:
    branches:
      - 'prod/*'
      - 'staging/*'
      - 'dev/*'
jobs:
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          ref: main
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: 'sts.amazonaws.com'
  prepare:
    runs-on: 'ubuntu-latest'
    outputs:
      target-env: ${{ steps.get-env-details.outputs.TARGET_ENV }}
      target-aws-account: ${{ steps.get-env-details.outputs.TARGET_AWS_ACCOUNT }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Identify Environment
      id: get-env-details
      run: |
        branch_name="${{ github.ref }}"
        branch_prefix="${branch_name#refs/heads/}"
        aws_acnt=""
        target_env=""
        case ${branch_prefix} in
          prod*)
            target_env="PROD"
            aws_acnt="${branch_prefix#prod/}"
            ;;
          staging*)
            target_env="STAGING"
            aws_acnt="${branch_prefix#staging/}"
            ;;
          dev*)
            target_env="DEV"
            aws_acnt="${branch_prefix#dev/}"
            ;;
        esac
        echo "TARGET_ENV=${target_env}" >> "$GITHUB_OUTPUT"
        echo "TARGET_AWS_ACCOUNT=${aws_acnt}" >> "$GITHUB_OUTPUT"
        echo "**TARGET ENV** = ${target_env}" >> "$GITHUB_STEP_SUMMARY"
        echo "**TARGET AWS ACCOUNT** = ${aws_acnt}" >> "$GITHUB_STEP_SUMMARY"
  start-prod:
    permissions:
      id-token: write
      contents: read
    needs: prepare
    if: startsWith(github.ref_name, 'prod') && github.ref_type == 'branch'
    name: Prod-AWS-Provision
    uses: ./.github/workflows/prod_aws.yml
    with:
      target-env: ${{ needs.prepare.outputs.target-env }}
      target-aws-account: ${{ needs.prepare.outputs.target-aws-account }}
  start-staging:
    permissions:
      id-token: write
      contents: read
    needs:
    - prepare
    if: startsWith(github.ref_name, 'staging') && github.ref_type == 'branch'
    name: Staging-AWS-Provision
    uses: ./.github/workflows/staging_aws.yml
    with:
      target-env: ${{ needs.prepare.outputs.target-env }}
      target-aws-account: ${{ needs.prepare.outputs.target-aws-account }}
  start-dev:
    permissions:
      id-token: write
      contents: read
    needs:
    - prepare
    if: startsWith(github.ref_name, 'dev') && github.ref_type == 'branch'
    name: Dev-AWS-Provision
    uses: ./.github/workflows/dev_aws.yml
    with:
      target-env: ${{ needs.prepare.outputs.target-env }}
      target-aws-account: ${{ needs.prepare.outputs.target-aws-account }}