name: Provision AWS Prod
on:
  workflow_call:
    inputs:
      target-env:
        description: "Target environment type, accepted values: PROD, STAGING, DEV"
        required: true
        type: string
      target-aws-account:
        description: "Target aws account for terraform account"
        required: true
        type: string
env:
  VAR_PREFIX: ${{format('{0}_{1}', inputs.target-env, inputs.target-aws-account)}}
  AWS_DEFAULT_REGION: ap-south-1
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate AWS MFA token
      id: generate-aws-mfa-otp
      env:
        ENV: ${{inputs.target-env}}
        AWS_ACNT: ${{inputs.target-aws-account}}
      uses:  ./.github/actions/generate_aws_mfa
      with:
        mfa-secret-key: ${{ secrets[format('{0}_AWS_MFA_TOTP_KEY', env.VAR_PREFIX)] }}
    - name: AWS Configure
      id: aws-configure
      env:
        AWS_ACCESS_KEY_ID_VAR: ${{ format('{0}_AWS_ACCESS_KEY_ID', env.VAR_PREFIX) }}
        AWS_SECRET_ACCESS_KEY_VAR: ${{ format('{0}_AWS_SECRET_ACCESS_KEY', env.VAR_PREFIX) }}
        AWS_MFA_SERIAL_NUMBER_VAR: ${{ format('{0}_AWS_MFA_SERIAL_NUMBER', env.VAR_PREFIX) }}
      run: |
        echo "VAR_PREFIX=${{env.VAR_PREFIX}}"
        echo "AWS_ACCESS_KEY_ID_VAR=${{env.AWS_ACCESS_KEY_ID_VAR}}"
        echo "AWS_SECRET_ACCESS_KEY_VAR=${{env.AWS_SECRET_ACCESS_KEY_VAR}}"
        echo "AWS_MFA_SERIAL_NUMBER_VAR=${{env.AWS_MFA_SERIAL_NUMBER_VAR}}"
        echo "AWS_ACCESS_KEY_ID = ${{ secrets[env.AWS_ACCESS_KEY_ID_VAR] }}"
        aws configure set aws_access_key_id ${{ secrets[env.AWS_ACCESS_KEY_ID_VAR] }}
        aws configure set aws_secret_access_key ${{ secrets[env.AWS_SECRET_ACCESS_KEY_VAR] }}
        aws configure set mfa_serial_number ${{ secrets[env.AWS_MFA_SERIAL_NUMBER_VAR] }}
        aws sts get-session-token --serial-number ${{ secrets[env.AWS_MFA_SERIAL_NUMBER_VAR] }} --token-code ${{ steps.generate-aws-mfa-otp.outputs.aws-mfa-otp }} > mfa_credentials.json
        export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId < mfa_credentials.json)
        export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey < mfa_credentials.json)
        export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken < mfa_credentials.json)
    - name: Test AWS
      id: test-aws
      run: aws s3 ls
  