## TODO
## 1. Write future improvements to keep track
name: Provision AWS Prod
on:
  workflow_call:
    inputs:
      target-env:
        description: "Target environment type, accepted values: PROD, STAGING, DEV"
        required: true
        type: string
      target-aws-account:
        description: "Target aws account for terraform account"
        required: true
        type: string
env:
  VAR_PREFIX: ${{format('{0}_{1}', inputs.target-env, inputs.target-aws-account)}}
  AWS_DEFAULT_REGION: ap-south-1
jobs:
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          ref: main
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: 'https://github.com/github'
  provision:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{env.AWS_DEFAULT_REGION}}
        role-to-assume: ${{secrets[format('{0}_AWS_DEPLOY_ROLE', env.VAR_PREFIX)]}}
        role-session-name: ghaSession
    - name: Test AWS
      id: test-aws
      run: aws s3 ls
  