name: Provision AWS Staging
on:
  workflow_call:
    inputs:
      target-env:
        description: "Target environment type, accepted values: PROD, STAGING, DEV"
        required: true
        type: string
      target-aws-account:
        description: "Target aws account for terraform account"
        required: true
        type: string
env:
  AWS_DEFAULT_REGION: ap-south-1
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{env.AWS_DEFAULT_REGION}}
        role-to-assume: ${{format('arn:aws:iam::{0}:role/gha-admin-role', inputs.target-aws-account)}}
        mask-aws-account-id: true
        role-session-name: ghaSession
    - name: Test AWS
      id: test-aws
      run: aws s3 ls
    - name: Get Short-lived Access Creds
      id: get-access-creds
      run: echo -e "ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}\nSECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
  